### ISSUE TITLE
Need help with connecting to project.

### ISSUE THREAD

**Issue by E-maniscool** [DavidtKate/DiscordMessengerUE4#2]
I downloaded the discord plugin and made a project, but I can't figure out how to connect the project to my discord server. Thanks!

**Comment by DavidtKate** [comment]
Hi E-maniscool, here is a [link](https://discordjs.guide/popular-topics/webhooks.html) to a small guide on how to get the webhook URL needed for DiscordMessenger to send messages to your discord server. If you have any more questions let me know, if not, let me know aswell so I can close this issue.

**Comment by E-maniscool** [comment]
Thank you I will check that out!
